// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/darck-theme.png
var resourceDarckThemePngData []byte
var resourceDarckThemePng = &fyne.StaticResource{
	StaticName:    "assets/darck-theme.png",
	StaticContent: resourceDarckThemePngData,
}

//go:embed assets/plumberFix.jpg
var resourcePlumberFixJpgData []byte
var resourcePlumberFixJpg = &fyne.StaticResource{
	StaticName:    "assets/plumberFix.jpg",
	StaticContent: resourcePlumberFixJpgData,
}

//go:embed assets/skilldar.png
var resourceSkilldarPngData []byte
var resourceSkilldarPng = &fyne.StaticResource{
	StaticName:    "assets/skilldar.png",
	StaticContent: resourceSkilldarPngData,
}

//go:embed assets/theme-lightl.png
var resourceThemeLightlPngData []byte
var resourceThemeLightlPng = &fyne.StaticResource{
	StaticName:    "assets/theme-lightl.png",
	StaticContent: resourceThemeLightlPngData,
}
